ssl:
  container_name: ssl
  ports:
    - "80:80/tcp"
    - "443:443/tcp"
  environment:
    DOMAINS: '
      mail.babedibubip.de
    '
    STAGE: 'production'
    SERVER_NAMES_HASH_BUCKET_SIZE: 64
    CLIENT_MAX_BODY_SIZE: 0
  image: steveltn/https-portal:1.6.1
  volumes:
    - ../DATA/ssl:/var/lib/https-portal
    # Enables a docker lookup of services for them to configure https themselves
    - /var/run/docker.sock:/var/run/docker.sock:ro
  tty: true
  stdin_open: true
  restart: always
