hook:
  container_name: mail-in-hook
  environment:
    MAIL_HOST: mail-in
    MAIL_PORT: 993
    MAIL_USER: mail@babedibubip.de
    MAIL_PASSWORD: Wdq4Yv0XSUlDUikXhCYm
    SQL_HOST: mail-db
    SQL_PORT: 3306
    SQL_USER: root
    SQL_PASSWORD: ElyIg2G9RKkEglizc58A
    SQL_DATABASE: mail
    SQL_TABLE: ingoing
  build: .
  # Only for dev
  #volumes:
  #  - ./process-mails.php:/process-mails.sh
  external_links:
    - mail-db
    - mail-in
  tty: true
  stdin_open: true
  restart: always
