web:
  container_name: dummy-frontpage_web
  ports:
    - "12080:80/tcp"
  environment:
    VIRTUAL_HOST: babedibubip.de
    VIRTUAL_PORT: 12080
    SERVER_NAMES_HASH_BUCKET_SIZE: 64
  image: nginx:alpine
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./www:/usr/share/nginx/html
    - ../DATA/dummy-frontpage/logs:/var/log/nginx
  links:
    - php
    - db
  tty: true
  stdin_open: true
  restart: always

php:
  ports:
    - "9000:9000"
  container_name: dummy-frontpage_php
  build: .
  dockerfile: Dockerfile-php
  volumes:
    - ./www:/html
  links:
    - db
  tty: true
  stdin_open: true
  restart: always

db:
  container_name: dummy-frontpage_db
  environment:
    MYSQL_ROOT_PASSWORD: P2VER3usSoD6dkWoHlQG
    MYSQL_DATABASE: honeypot
  image: mysql:5.7
  volumes:
    - ../DATA/dummy-frontpage/mysql:/var/lib/mysql
  tty: true
  stdin_open: true
  restart: always

phpmyadmin:
  container_name: dummy-frontpage_phpmyadmin
  ports:
    - "13080:80/tcp"
  #environment:
  #  VIRTUAL_HOST: mysqladmin1337.famboot.de
  #  VIRTUAL_PORT: 80
  image: phpmyadmin/phpmyadmin
  links:
    - db
  tty: true
  stdin_open: true
  restart: always
